language: python

python:
  - 3.8

services:
  - postgresql

env:
  - DJANGO=3.0

before_install:
  - export DJANGO_SETTINGS_MODULE="soccer_website.settings"
  - export DATABASE_URL=postgres://postgres:postgres@localhost/travisdb

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - python manage.py migrate --no-input

script: python manage.py test

notifications:
  email:
    on_success: change
    on_failure: change
