language: python

python:
  - 3.8

install:
  - pip install -r requirements.txt

services:
  - postgresql

env:
  - export DJANGO=3.0
  - export DABATASE_URL=postgres://postgres@localhost/travisdb

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - python games/manage.py migrate --no-input

script: python manage.py test
