language: python

python:
  - 3.8

install:
  - pip install -r requirements.txt

services:
  - postgresql

env:
  - DJANGO=3.0 DABATASE_URL=postgres://postgres:postgres@localhost/travisdb

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - python manage.py migrate --no-input

script: python manage.py test

notifications:
  email:
    recipients:
      - eitan.simler@gmail.com
    on_success: never
    on_failure: always
