# Generated by Django 3.0 on 2019-12-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Roble Field', max_length=100)),
                ('datetime', models.DateTimeField(verbose_name='when')),
                ('max_players', models.PositiveSmallIntegerField(default=18)),
                ('players', models.CharField(max_length=360)),
            ],
        ),
    ]
