# Generated by Django 3.0 on 2019-12-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
    ]
