# Generated by Django 3.0 on 2019-12-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='opted_for_waitlist',
            field=models.BooleanField(default=False),
        ),
    ]
