# Generated by Django 3.0 on 2019-12-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20191207_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='opted_for_waitlist',
            field=models.BooleanField(default=False, verbose_name='Start on Waitlist'),
        ),
    ]
