# Generated by Django 3.0.2 on 2020-01-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0005_auto_20191207_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.PositiveSmallIntegerField(default=14),
        ),
    ]
